/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapp;

import java.awt.event.*;
/**
 *
 * @author zlux
 */
public class school_view extends javax.swing.JFrame {

    /**
     * Creates new form school_view
     */
    public school_view() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        lb_school_name = new javax.swing.JLabel();
        lb_school_id = new javax.swing.JLabel();
        edit_school_name = new javax.swing.JTextField();
        edit_school_id = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_school_name.setText("school name:");

        lb_school_id.setText("school ID:");

        btn_add.setText("add");
        /*
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
         */
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_school_name)
                                .addGap(32, 32, 32)
                                .addComponent(edit_school_name))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_school_id)
                                .addGap(52, 52, 52)
                                .addComponent(edit_school_id, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_add)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_school_name)
                    .addComponent(edit_school_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_school_id)
                    .addComponent(edit_school_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(btn_add)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    /*
    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    */
    
    //instead we add a function which called be called from the controller class
    public void btn_add_school_add_listener(ActionListener p)
    {
        btn_add.addActionListener(p);
    }
    
    public void saveAllData()
    {
        school_id = edit_school_id.getText();
        school_name = edit_school_name.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JTextField edit_school_id;
    private javax.swing.JTextField edit_school_name;
    private javax.swing.JLabel lb_school_id;
    private javax.swing.JLabel lb_school_name;
    // End of variables declaration//GEN-END:variables

    public String school_id;
    public String school_name;
}
