/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapp;

/**
 *
 * @author zlux
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public view() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_add_school = new javax.swing.JButton();
        btn_view_school = new javax.swing.JButton();
        btn_add_teacher = new javax.swing.JButton();
        btn_view_teacher = new javax.swing.JButton();
        lb_banner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_add_school.setText("add_school");
        btn_add_school.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_schoolActionPerformed(evt);
            }
        });

        btn_view_school.setText("view_school");
        btn_view_school.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_view_schoolActionPerformed(evt);
            }
        });

        btn_add_teacher.setText("add_teacher");
        btn_add_teacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_teacherActionPerformed(evt);
            }
        });

        btn_view_teacher.setText("view_teacher");
        btn_view_teacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_view_teacherActionPerformed(evt);
            }
        });

        lb_banner.setText("Welcome to Sydney!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_add_school)
                    .addComponent(btn_view_school)
                    .addComponent(btn_add_teacher)
                    .addComponent(btn_view_teacher))
                .addGap(67, 67, 67)
                .addComponent(lb_banner, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_banner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_add_school)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_view_school)
                        .addGap(58, 58, 58)
                        .addComponent(btn_add_teacher)
                        .addGap(27, 27, 27)
                        .addComponent(btn_view_teacher)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        btn_add_school.getAccessibleContext().setAccessibleName("btn_add_school");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_add_schoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_schoolActionPerformed
        // TODO add your handling code here:
        school_view schoolview = new school_view();
        schoolview.setVisible(true);
        
        schoolview.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btn_add_schoolActionPerformed

    private void btn_view_schoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_view_schoolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view_schoolActionPerformed

    private void btn_add_teacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_teacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_add_teacherActionPerformed

    private void btn_view_teacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_view_teacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view_teacherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_school;
    private javax.swing.JButton btn_add_teacher;
    private javax.swing.JButton btn_view_school;
    private javax.swing.JButton btn_view_teacher;
    private javax.swing.JLabel lb_banner;
    // End of variables declaration//GEN-END:variables
}
